@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.peco2282.bcreborn.api.serialization;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;